<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [64]:
lista_random = np.random.randint(1,101,100)

print(lista_random)

print('\n')

print(f'Valor max da lista: {lista_random.max()}')
print(f'Valor min da lista: {lista_random.min()}')

[ 69  82  92  67  92  45  59  16  70  21  31  47  19  75  86  68  43   4
  33  94  68  14  71  47  14  93  43  31  87  35  78  14  44  91  20  38
  39  97  45  94  46  63  64  96  40  21  99  54  53  15  28  25  12  46
  65  43  79   4  13  89  13  41  69  14  20  12   1  37  42  95  71  95
  96  40  56  64  46  74  96  92  77  34  70  95  42 100   2  12  45  58
  10  75  63  91  93  96  88  78  54  56]


Valor max da lista: 100
Valor min da lista: 1


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [58]:
def modulo(lista_vetor):
    modulo = np.sqrt((lista_vetor**2).sum())
    
    return modulo

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [24]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)



1.6666666666666667

In [23]:
# Solução
def calculate_eqm(y_prediction, y_i):
    EQM = ((y_prediction - y_i)**2).sum()/y_prediction.size
    
    return EQM 

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [27]:
def matriz_binaria(linha,coluna):
    matriz = np.zeros((linha,coluna))

    matriz[:,0] = 1
    matriz[:,-1] = 1
    matriz[0,:] = 1
    matriz[-1,:] = 1

    return matriz

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [29]:
def borda_zero(matriz):
    matriz = np.pad(matriz, pad_width=1, mode='constant', constant_values=0)

    return matriz

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [32]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [42]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [43]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-0.0012191802816346646

In [44]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 1.22192363, -1.5237919 ,  0.86338038, ...,  1.30727673,
        -0.47753703, -1.0596497 ],
       [ 0.71970543, -0.7777961 , -0.35406794, ..., -0.70405225,
        -0.73368643, -1.03462781],
       [ 1.87043483, -0.05764714, -0.22416848, ...,  1.12671475,
         3.14410314,  0.64255076],
       ...,
       [-0.22334951,  0.51702055,  0.01297827, ...,  0.55214192,
        -0.51030982,  0.024972  ],
       [ 0.04778741, -0.33813906,  0.79085906, ..., -1.71204669,
        -0.46380442,  0.47341534],
       [-0.73687625,  1.15976271, -1.04379878, ...,  0.73042385,
        -0.83005176,  0.23064209]])

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

In [46]:
# Solução
def process_EEG_signal(X):
    processamento = X - X.mean()

    return X_processado

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [102]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[ 0.53608003,  0.48336967,  1.17573028, ..., -1.11188503,
         0.12994453,  0.2264955 ],
       [ 0.85475904,  0.48164439, -0.96497623, ...,  2.34686127,
         0.19891967,  0.28377792],
       [-0.81707066,  0.84886588, -0.65427146, ..., -0.06429173,
         1.54409582,  0.26469928],
       ...,
       [ 1.22276896, -1.31065445,  0.00846432, ..., -0.81517445,
        -2.43100246,  0.17707571],
       [-0.87393729, -0.95585886, -1.21447318, ...,  0.13868495,
         0.47155413, -0.59201319],
       [-0.13897985,  0.36297142, -0.50115789, ...,  1.43945726,
         0.9565138 ,  0.25769097]])

In [103]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [89]:
is_outlier

array([[False,  True, False, ..., False,  True,  True],
       [False,  True,  True, ...,  True,  True, False],
       [False, False, False, ...,  True,  True,  True],
       ...,
       [ True, False,  True, ..., False, False,  True],
       [False,  True,  True, ...,  True, False, False],
       [False, False, False, ...,  True,  True,  True]])

In [104]:
outliers_count

39

In [100]:
outliers

array([-2.80150007, -3.44770318, -2.72982224, -2.96063501, -2.8173526 ,
       -3.34612695, -2.77052458,  2.68135936, -2.9765439 ,  2.65080775,
       -3.07581496, -2.67255198, -2.81966073, -2.99195126, -3.8442743 ,
       -3.45030623, -2.71650502,  2.61795789,  2.84704157,  3.30562373,
        2.88248995, -2.4643169 , -2.8148201 , -2.84299316,  2.76589655,
        2.93960039,  2.79742937,  2.7342894 , -4.02773958, -3.17212239,
       -2.82746338, -2.39773553])

In [99]:
# Solução

def locate_outliers(distribuicao):
    quartil_1 = np.quantile(distribuicao, 0.25, axis=0)
    quartil_3 = np.quantile(distribuicao, 0.75, axis=0)
    iqr = quartil_3 - quartil_1
    is_outlier = ((distribuicao < (quartil_1 - iqr.dot(1.5)))) | (distribuicao > (quartil_3 + iqr.dot(1.5)))
    outliers_count = (distribuicao[is_outlier]).size
    outliers = distribuicao[is_outlier]
    
    return is_outlier, outliers_count, outliers

is_outlier, outliers_count, outliers = locate_outliers(X)

outliers_count


32

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [47]:
vetor = np.arange(1, 22, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [51]:
lista_random2 = np.random.rand(10)
lista_random2

array([0.20178418, 0.00264288, 0.25336517, 0.12129046, 0.13790263,
       0.47530098, 0.16261393, 0.36110497, 0.3074067 , 0.8428488 ])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [53]:
def normaliza(conjunto):
    normalizado = (conjunto - conjunto.mean())/conjunto.std()

    return normalizado

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [52]:
def metricas_notas(lista_notas):
    media = lista_notas.mean()
    desvio_padrao = lista_notas.std()
    maiores_7 = (lista_notas[lista_notas>7]).size
    reprovados = (lista_notas[lista_notas<5]).size
    min = lista_notas.min()
    max = lista_notas.max()

    return np.array([media, desvio_padrao, maiores_7, reprovados, min, max])